### ISSUE TITLE
[BUG] `KeyError: 'reference_database_name'` when running summarize

### ISSUE THREAD

**Issue by jfy133** [pha4ge/hAMRonization#80]
**Describe the bug**

I get the following error when running with `summarize`

```
Warning: <_io.TextIOWrapper name='WAL001-megahit.mapping.potential.ARG.deeparg.json' mode='r' encoding='UTF-8'> report is empty
Traceback (most recent call last):
  File "/home/jfellows/ccdata/users/JFellows/bin/miniconda3/envs/hamronization/bin/hamronize", line 8, in <module>
    sys.exit(main())
  File "/home/jfellows/ccdata/users/JFellows/bin/miniconda3/envs/hamronization/lib/python3.10/site-packages/hAMRonization/hamronize.py", line 7, in main
    hAMRonization.Interfaces.generic_cli_interface()
  File "/home/jfellows/ccdata/users/JFellows/bin/miniconda3/envs/hamronization/lib/python3.10/site-packages/hAMRonization/Interfaces.py", line 299, in generic_cli_interface
    hAMRonization.summarize.summarize_reports(
  File "/home/jfellows/ccdata/users/JFellows/bin/miniconda3/envs/hamronization/lib/python3.10/site-packages/hAMRonization/summarize.py", line 752, in summarize_reports
    combined_reports = combined_reports.sort_values(
  File "/home/jfellows/ccdata/users/JFellows/bin/miniconda3/envs/hamronization/lib/python3.10/site-packages/pandas/util/_decorators.py", line 317, in wrapper
    return func(*args, **kwargs)
  File "/home/jfellows/ccdata/users/JFellows/bin/miniconda3/envs/hamronization/lib/python3.10/site-packages/pandas/core/frame.py", line 6886, in sort_values
    keys = [self._get_label_or_level_values(x, axis=axis) for x in by]
  File "/home/jfellows/ccdata/users/JFellows/bin/miniconda3/envs/hamronization/lib/python3.10/site-packages/pandas/core/frame.py", line 6886, in <listcomp>
    keys = [self._get_label_or_level_values(x, axis=axis) for x in by]
  File "/home/jfellows/ccdata/users/JFellows/bin/miniconda3/envs/hamronization/lib/python3.10/site-packages/pandas/core/generic.py", line 1849, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'reference_database_name'
```

**Input**
```
hamronize \
    summarize \
    <huge_list_of_jsons> \
    -t interactive \
     \
    -o hamronization_combined_report.html
```

**Input file**
I can send a zip of the entire privately if necessary (includes unpublished data)

**Error log**
See above

**hAMRonization Version**
1.1.0

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: SUSE Linux Enterprise High Performance Computing 15 SP1
 - Version: hAMRronization 1.1.0

**Additional context**
If applicable, include dependency versions such as pandas version and Python version.

**Comment by fmaguire** [comment]
Ah damn, sorry, I thought I'd solved that issue/covered it with tests. Not quite sure how this is still 

Does the same error occur if you run `hamronize summarize` on just `WAL001-megahit.mapping.potential.ARG.deeparg.json` or only with the big list of jsons? 

If the former could you send me just that output file (to finlay.maguire@dal.ca) and if the latter the big ole zip?

**Comment by jfy133** [comment]
Yes, only WAL001-megahit, but strangely it seems to happen in all cases, e.g. `VLC009-metaspades.mapping.potential.ARG.deeparg.json` which does have hits.

I'll send you the zip and you can test everything. Happy to also test any dev versions!

**Comment by jfy133** [comment]
1. OK! I will test this :)
2. Ah yes correct sorry, the JSONs in the ZIP were still from 1.0.3 - It took a few days for the pipeline to run, so didn't want to run the whole thing again with 1.1.0 to find the same/different summarize issue :sweat_smile: . I can try to take a few and re-generate them with 1.1.0  to double check now though

**Comment by jfy133** [comment]
@fmaguire I can confirm https://github.com/pha4ge/hAMRonization/commit/761fe771865096fbf7b68dcda1ee51816a3055f1 fixes the bug, and that re-running e.g. `harmonizate deeparg` on an 'empty' outputfile produces the correct empty JSON of `[]`.

Once this version is released on bioconda (I sped that up for 1.1.0 this morning btw :grimacing: ), I will update our nf-core nextflow module and re-run the full pipeline again and let you know how well it performs.

This PR can be closed now!

**Comment by jfy133** [comment]
oh and thanks for the quick turnaround :D

**Comment by fmaguire** [comment]
(although it does seem the badges on the README aren't updating for some reason...)

**Comment by fmaguire** [comment]
Updated in bioconda now: https://github.com/bioconda/bioconda-recipes/pull/37140
